trigger:
  branches:
    include:
      - master
  paths:
    include:
      - site.hs

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p ~/.local/bin
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  displayName: Install Stack

- script: |
    export PATH=$HOME/.local/bin:$PATH
    stack --no-terminal --install-ghc test --only-dependencies
  displayName: Build Dependencies

- script: |
    export PATH=$HOME/.local/bin/$PATH
    stack build
  displayName: Build Site Executable

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'site'
    publishLocation: 'Container'
